/* Automatically generated by tree-sitter v0.25.1 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 60
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 50
#define ALIAS_COUNT 0
#define TOKEN_COUNT 32
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 19
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 17
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_SEMI = 1,
  anon_sym_print = 2,
  anon_sym_LPAREN = 3,
  anon_sym_RPAREN = 4,
  anon_sym_query = 5,
  anon_sym_with = 6,
  anon_sym_requires = 7,
  anon_sym_role = 8,
  anon_sym_let = 9,
  anon_sym_COLON = 10,
  anon_sym_EQ = 11,
  anon_sym_String = 12,
  anon_sym_Session = 13,
  anon_sym_construct_session = 14,
  sym_bop_eq = 15,
  sym_bop_lt = 16,
  sym_bop_gt = 17,
  sym_bop_and = 18,
  sym_bop_or = 19,
  sym_primary_true_expr = 20,
  sym_primary_false_expr = 21,
  anon_sym_q_DQUOTE = 22,
  anon_sym_DQUOTE = 23,
  anon_sym_LBRACE = 24,
  anon_sym_RBRACE = 25,
  sym_query_string_segment = 26,
  anon_sym_user = 27,
  anon_sym_assistant = 28,
  anon_sym_system = 29,
  sym_llm = 30,
  sym_identifier = 31,
  sym_source_file = 32,
  sym_statement = 33,
  sym_print_statement = 34,
  sym_query_statement = 35,
  sym_decl_statement = 36,
  sym_type = 37,
  sym_primitive_type = 38,
  sym_expr = 39,
  sym_construct_session_expr = 40,
  sym_bop_expr = 41,
  sym_primary_expr = 42,
  sym_primary_parenthesized_expr = 43,
  sym_primary_identifier_expr = 44,
  sym_query_string = 45,
  sym_query_decl = 46,
  sym_role = 47,
  aux_sym_source_file_repeat1 = 48,
  aux_sym_query_string_repeat1 = 49,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SEMI] = ";",
  [anon_sym_print] = "print",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_query] = "query",
  [anon_sym_with] = "with",
  [anon_sym_requires] = "requires",
  [anon_sym_role] = "role",
  [anon_sym_let] = "let",
  [anon_sym_COLON] = ":",
  [anon_sym_EQ] = "=",
  [anon_sym_String] = "String",
  [anon_sym_Session] = "Session",
  [anon_sym_construct_session] = "construct_session",
  [sym_bop_eq] = "bop_eq",
  [sym_bop_lt] = "bop_lt",
  [sym_bop_gt] = "bop_gt",
  [sym_bop_and] = "bop_and",
  [sym_bop_or] = "bop_or",
  [sym_primary_true_expr] = "primary_true_expr",
  [sym_primary_false_expr] = "primary_false_expr",
  [anon_sym_q_DQUOTE] = "q\"",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_query_string_segment] = "query_string_segment",
  [anon_sym_user] = "user",
  [anon_sym_assistant] = "assistant",
  [anon_sym_system] = "system",
  [sym_llm] = "llm",
  [sym_identifier] = "identifier",
  [sym_source_file] = "source_file",
  [sym_statement] = "statement",
  [sym_print_statement] = "print_statement",
  [sym_query_statement] = "query_statement",
  [sym_decl_statement] = "decl_statement",
  [sym_type] = "type",
  [sym_primitive_type] = "primitive_type",
  [sym_expr] = "expr",
  [sym_construct_session_expr] = "construct_session_expr",
  [sym_bop_expr] = "bop_expr",
  [sym_primary_expr] = "primary_expr",
  [sym_primary_parenthesized_expr] = "primary_parenthesized_expr",
  [sym_primary_identifier_expr] = "primary_identifier_expr",
  [sym_query_string] = "query_string",
  [sym_query_decl] = "query_decl",
  [sym_role] = "role",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_query_string_repeat1] = "query_string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_print] = anon_sym_print,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_query] = anon_sym_query,
  [anon_sym_with] = anon_sym_with,
  [anon_sym_requires] = anon_sym_requires,
  [anon_sym_role] = anon_sym_role,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_String] = anon_sym_String,
  [anon_sym_Session] = anon_sym_Session,
  [anon_sym_construct_session] = anon_sym_construct_session,
  [sym_bop_eq] = sym_bop_eq,
  [sym_bop_lt] = sym_bop_lt,
  [sym_bop_gt] = sym_bop_gt,
  [sym_bop_and] = sym_bop_and,
  [sym_bop_or] = sym_bop_or,
  [sym_primary_true_expr] = sym_primary_true_expr,
  [sym_primary_false_expr] = sym_primary_false_expr,
  [anon_sym_q_DQUOTE] = anon_sym_q_DQUOTE,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_query_string_segment] = sym_query_string_segment,
  [anon_sym_user] = anon_sym_user,
  [anon_sym_assistant] = anon_sym_assistant,
  [anon_sym_system] = anon_sym_system,
  [sym_llm] = sym_llm,
  [sym_identifier] = sym_identifier,
  [sym_source_file] = sym_source_file,
  [sym_statement] = sym_statement,
  [sym_print_statement] = sym_print_statement,
  [sym_query_statement] = sym_query_statement,
  [sym_decl_statement] = sym_decl_statement,
  [sym_type] = sym_type,
  [sym_primitive_type] = sym_primitive_type,
  [sym_expr] = sym_expr,
  [sym_construct_session_expr] = sym_construct_session_expr,
  [sym_bop_expr] = sym_bop_expr,
  [sym_primary_expr] = sym_primary_expr,
  [sym_primary_parenthesized_expr] = sym_primary_parenthesized_expr,
  [sym_primary_identifier_expr] = sym_primary_identifier_expr,
  [sym_query_string] = sym_query_string,
  [sym_query_decl] = sym_query_decl,
  [sym_role] = sym_role,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_query_string_repeat1] = aux_sym_query_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_print] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_query] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_with] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_requires] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_role] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_String] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Session] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_construct_session] = {
    .visible = true,
    .named = false,
  },
  [sym_bop_eq] = {
    .visible = true,
    .named = true,
  },
  [sym_bop_lt] = {
    .visible = true,
    .named = true,
  },
  [sym_bop_gt] = {
    .visible = true,
    .named = true,
  },
  [sym_bop_and] = {
    .visible = true,
    .named = true,
  },
  [sym_bop_or] = {
    .visible = true,
    .named = true,
  },
  [sym_primary_true_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_primary_false_expr] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_q_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_query_string_segment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_user] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_assistant] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_system] = {
    .visible = true,
    .named = false,
  },
  [sym_llm] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_print_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_query_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_decl_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_primitive_type] = {
    .visible = true,
    .named = true,
  },
  [sym_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_construct_session_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_bop_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_primary_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_primary_parenthesized_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_primary_identifier_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_query_string] = {
    .visible = true,
    .named = true,
  },
  [sym_query_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_role] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_query_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_context = 1,
  field_decl = 2,
  field_decl_expr = 3,
  field_decl_identifier = 4,
  field_decl_type = 5,
  field_expr_in_parentheses = 6,
  field_ident = 7,
  field_left = 8,
  field_llm = 9,
  field_op = 10,
  field_query_clause = 11,
  field_requires_clause = 12,
  field_right = 13,
  field_role_clause = 14,
  field_segment = 15,
  field_session = 16,
  field_session_type = 17,
  field_string_type = 18,
  field_type = 19,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_context] = "context",
  [field_decl] = "decl",
  [field_decl_expr] = "decl_expr",
  [field_decl_identifier] = "decl_identifier",
  [field_decl_type] = "decl_type",
  [field_expr_in_parentheses] = "expr_in_parentheses",
  [field_ident] = "ident",
  [field_left] = "left",
  [field_llm] = "llm",
  [field_op] = "op",
  [field_query_clause] = "query_clause",
  [field_requires_clause] = "requires_clause",
  [field_right] = "right",
  [field_role_clause] = "role_clause",
  [field_segment] = "segment",
  [field_session] = "session",
  [field_session_type] = "session_type",
  [field_string_type] = "string_type",
  [field_type] = "type",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 4},
  [4] = {.index = 6, .length = 3},
  [5] = {.index = 9, .length = 1},
  [6] = {.index = 10, .length = 1},
  [7] = {.index = 11, .length = 1},
  [8] = {.index = 12, .length = 1},
  [9] = {.index = 13, .length = 1},
  [10] = {.index = 14, .length = 2},
  [11] = {.index = 16, .length = 4},
  [12] = {.index = 20, .length = 6},
  [13] = {.index = 26, .length = 6},
  [14] = {.index = 32, .length = 3},
  [15] = {.index = 35, .length = 8},
  [16] = {.index = 43, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_ident, 0},
  [1] =
    {field_expr_in_parentheses, 1},
  [2] =
    {field_context, 3},
    {field_query_clause, 0},
    {field_query_clause, 2},
    {field_session, 1},
  [6] =
    {field_left, 0},
    {field_op, 1},
    {field_right, 2},
  [9] =
    {field_string_type, 0},
  [10] =
    {field_session_type, 0},
  [11] =
    {field_llm, 2},
  [12] =
    {field_segment, 0},
  [13] =
    {field_decl, 0},
  [14] =
    {field_decl, 1, .inherited = true},
    {field_segment, 1, .inherited = true},
  [16] =
    {field_decl, 0, .inherited = true},
    {field_decl, 1, .inherited = true},
    {field_segment, 0, .inherited = true},
    {field_segment, 1, .inherited = true},
  [20] =
    {field_context, 3},
    {field_query_clause, 0},
    {field_query_clause, 2},
    {field_requires_clause, 4},
    {field_requires_clause, 5},
    {field_session, 1},
  [26] =
    {field_context, 3},
    {field_query_clause, 0},
    {field_query_clause, 2},
    {field_role_clause, 4},
    {field_role_clause, 5},
    {field_session, 1},
  [32] =
    {field_decl_expr, 5},
    {field_decl_identifier, 1},
    {field_decl_type, 3},
  [35] =
    {field_context, 3},
    {field_query_clause, 0},
    {field_query_clause, 2},
    {field_requires_clause, 4},
    {field_requires_clause, 5},
    {field_role_clause, 6},
    {field_role_clause, 7},
    {field_session, 1},
  [43] =
    {field_decl_identifier, 2},
    {field_type, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(82);
      ADVANCE_MAP(
        '"', 109,
        '&', 5,
        '(', 85,
        ')', 86,
        ':', 92,
        ';', 83,
        '<', 100,
        '=', 94,
        '>', 101,
        'S', 21,
        'a', 55,
        'c', 41,
        'f', 9,
        'g', 45,
        'l', 17,
        'p', 50,
        'q', 2,
        'r', 12,
        's', 80,
        't', 47,
        'u', 63,
        'w', 27,
        '{', 110,
        '|', 81,
        '}', 111,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(109);
      if (lookahead == '{') ADVANCE(110);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(112);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(113);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(108);
      if (lookahead == 'u') ADVANCE(18);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '&', 5,
        '(', 85,
        ')', 86,
        ';', 83,
        '<', 100,
        '=', 6,
        '>', 101,
        'c', 128,
        'f', 119,
        't', 130,
        '|', 81,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 4:
      ADVANCE_MAP(
        '&', 5,
        ')', 86,
        ';', 83,
        '<', 100,
        '=', 6,
        '>', 101,
        'r', 42,
        'w', 27,
        '|', 81,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      END_STATE();
    case 5:
      if (lookahead == '&') ADVANCE(102);
      END_STATE();
    case 6:
      if (lookahead == '=') ADVANCE(99);
      END_STATE();
    case 7:
      if (lookahead == '=') ADVANCE(93);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 8:
      if (lookahead == '_') ADVANCE(62);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(33);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(39);
      END_STATE();
    case 11:
      if (lookahead == 'c') ADVANCE(72);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(46);
      if (lookahead == 'o') ADVANCE(32);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(90);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(104);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(106);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(34);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(68);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(49);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(48);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(54);
      END_STATE();
    case 21:
      if (lookahead == 'e') ADVANCE(64);
      if (lookahead == 't') ADVANCE(53);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(66);
      END_STATE();
    case 23:
      if (lookahead == 'g') ADVANCE(95);
      END_STATE();
    case 24:
      if (lookahead == 'h') ADVANCE(88);
      END_STATE();
    case 25:
      if (lookahead == 'i') ADVANCE(38);
      END_STATE();
    case 26:
      if (lookahead == 'i') ADVANCE(35);
      END_STATE();
    case 27:
      if (lookahead == 'i') ADVANCE(69);
      END_STATE();
    case 28:
      if (lookahead == 'i') ADVANCE(52);
      END_STATE();
    case 29:
      if (lookahead == 'i') ADVANCE(43);
      END_STATE();
    case 30:
      if (lookahead == 'i') ADVANCE(44);
      END_STATE();
    case 31:
      if (lookahead == 'i') ADVANCE(61);
      END_STATE();
    case 32:
      if (lookahead == 'l') ADVANCE(13);
      END_STATE();
    case 33:
      if (lookahead == 'l') ADVANCE(59);
      END_STATE();
    case 34:
      if (lookahead == 'm') ADVANCE(116);
      END_STATE();
    case 35:
      if (lookahead == 'n') ADVANCE(23);
      END_STATE();
    case 36:
      if (lookahead == 'n') ADVANCE(96);
      END_STATE();
    case 37:
      if (lookahead == 'n') ADVANCE(97);
      END_STATE();
    case 38:
      if (lookahead == 'n') ADVANCE(70);
      END_STATE();
    case 39:
      if (lookahead == 'n') ADVANCE(71);
      END_STATE();
    case 40:
      if (lookahead == 'n') ADVANCE(60);
      END_STATE();
    case 41:
      if (lookahead == 'o') ADVANCE(40);
      END_STATE();
    case 42:
      if (lookahead == 'o') ADVANCE(32);
      END_STATE();
    case 43:
      if (lookahead == 'o') ADVANCE(36);
      END_STATE();
    case 44:
      if (lookahead == 'o') ADVANCE(37);
      END_STATE();
    case 45:
      if (lookahead == 'p') ADVANCE(67);
      END_STATE();
    case 46:
      if (lookahead == 'q') ADVANCE(78);
      END_STATE();
    case 47:
      if (lookahead == 'r') ADVANCE(77);
      END_STATE();
    case 48:
      if (lookahead == 'r') ADVANCE(114);
      END_STATE();
    case 49:
      if (lookahead == 'r') ADVANCE(79);
      END_STATE();
    case 50:
      if (lookahead == 'r') ADVANCE(25);
      END_STATE();
    case 51:
      if (lookahead == 'r') ADVANCE(76);
      END_STATE();
    case 52:
      if (lookahead == 'r') ADVANCE(20);
      END_STATE();
    case 53:
      if (lookahead == 'r') ADVANCE(26);
      END_STATE();
    case 54:
      if (lookahead == 's') ADVANCE(89);
      END_STATE();
    case 55:
      if (lookahead == 's') ADVANCE(56);
      END_STATE();
    case 56:
      if (lookahead == 's') ADVANCE(31);
      END_STATE();
    case 57:
      if (lookahead == 's') ADVANCE(29);
      END_STATE();
    case 58:
      if (lookahead == 's') ADVANCE(75);
      END_STATE();
    case 59:
      if (lookahead == 's') ADVANCE(15);
      END_STATE();
    case 60:
      if (lookahead == 's') ADVANCE(74);
      END_STATE();
    case 61:
      if (lookahead == 's') ADVANCE(73);
      END_STATE();
    case 62:
      if (lookahead == 's') ADVANCE(22);
      END_STATE();
    case 63:
      if (lookahead == 's') ADVANCE(19);
      END_STATE();
    case 64:
      if (lookahead == 's') ADVANCE(57);
      END_STATE();
    case 65:
      if (lookahead == 's') ADVANCE(30);
      END_STATE();
    case 66:
      if (lookahead == 's') ADVANCE(65);
      END_STATE();
    case 67:
      if (lookahead == 't') ADVANCE(117);
      END_STATE();
    case 68:
      if (lookahead == 't') ADVANCE(91);
      END_STATE();
    case 69:
      if (lookahead == 't') ADVANCE(24);
      END_STATE();
    case 70:
      if (lookahead == 't') ADVANCE(84);
      END_STATE();
    case 71:
      if (lookahead == 't') ADVANCE(115);
      END_STATE();
    case 72:
      if (lookahead == 't') ADVANCE(8);
      END_STATE();
    case 73:
      if (lookahead == 't') ADVANCE(10);
      END_STATE();
    case 74:
      if (lookahead == 't') ADVANCE(51);
      END_STATE();
    case 75:
      if (lookahead == 't') ADVANCE(16);
      END_STATE();
    case 76:
      if (lookahead == 'u') ADVANCE(11);
      END_STATE();
    case 77:
      if (lookahead == 'u') ADVANCE(14);
      END_STATE();
    case 78:
      if (lookahead == 'u') ADVANCE(28);
      END_STATE();
    case 79:
      if (lookahead == 'y') ADVANCE(87);
      END_STATE();
    case 80:
      if (lookahead == 'y') ADVANCE(58);
      END_STATE();
    case 81:
      if (lookahead == '|') ADVANCE(103);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_print);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_query);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_with);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_requires);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_role);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(99);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_String);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_Session);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_construct_session);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_construct_session);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_bop_eq);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_bop_lt);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_bop_gt);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_bop_and);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_bop_or);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_primary_true_expr);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_primary_true_expr);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_primary_false_expr);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_primary_false_expr);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(anon_sym_q_DQUOTE);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_query_string_segment);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(112);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(113);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_query_string_segment);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(113);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(anon_sym_user);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(anon_sym_assistant);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(anon_sym_system);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_llm);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '_') ADVANCE(135);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(125);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(137);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(105);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(107);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(136);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(129);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(134);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(132);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(98);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(126);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(127);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(139);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(140);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(138);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(124);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(122);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(123);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(133);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(118);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(131);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(121);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(120);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 3},
  [3] = {.lex_state = 3},
  [4] = {.lex_state = 3},
  [5] = {.lex_state = 3},
  [6] = {.lex_state = 3},
  [7] = {.lex_state = 3},
  [8] = {.lex_state = 3},
  [9] = {.lex_state = 3},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 4},
  [12] = {.lex_state = 4},
  [13] = {.lex_state = 4},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 4},
  [16] = {.lex_state = 4},
  [17] = {.lex_state = 4},
  [18] = {.lex_state = 4},
  [19] = {.lex_state = 4},
  [20] = {.lex_state = 4},
  [21] = {.lex_state = 4},
  [22] = {.lex_state = 3},
  [23] = {.lex_state = 3},
  [24] = {.lex_state = 3},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 7},
  [45] = {.lex_state = 7},
  [46] = {.lex_state = 7},
  [47] = {.lex_state = 7},
  [48] = {.lex_state = 7},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 7},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_print] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_query] = ACTIONS(1),
    [anon_sym_with] = ACTIONS(1),
    [anon_sym_requires] = ACTIONS(1),
    [anon_sym_role] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_String] = ACTIONS(1),
    [anon_sym_Session] = ACTIONS(1),
    [anon_sym_construct_session] = ACTIONS(1),
    [sym_bop_eq] = ACTIONS(1),
    [sym_bop_lt] = ACTIONS(1),
    [sym_bop_gt] = ACTIONS(1),
    [sym_bop_and] = ACTIONS(1),
    [sym_bop_or] = ACTIONS(1),
    [sym_primary_true_expr] = ACTIONS(1),
    [sym_primary_false_expr] = ACTIONS(1),
    [anon_sym_q_DQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_user] = ACTIONS(1),
    [anon_sym_assistant] = ACTIONS(1),
    [anon_sym_system] = ACTIONS(1),
    [sym_llm] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(49),
    [sym_statement] = STATE(10),
    [sym_print_statement] = STATE(42),
    [sym_query_statement] = STATE(42),
    [sym_decl_statement] = STATE(42),
    [aux_sym_source_file_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_print] = ACTIONS(5),
    [anon_sym_query] = ACTIONS(7),
    [anon_sym_let] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_construct_session,
    ACTIONS(17), 1,
      sym_identifier,
    STATE(21), 1,
      sym_expr,
    ACTIONS(15), 2,
      sym_primary_true_expr,
      sym_primary_false_expr,
    STATE(11), 2,
      sym_primary_parenthesized_expr,
      sym_primary_identifier_expr,
    STATE(13), 3,
      sym_construct_session_expr,
      sym_bop_expr,
      sym_primary_expr,
  [26] = 7,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_construct_session,
    ACTIONS(17), 1,
      sym_identifier,
    STATE(23), 1,
      sym_expr,
    ACTIONS(15), 2,
      sym_primary_true_expr,
      sym_primary_false_expr,
    STATE(11), 2,
      sym_primary_parenthesized_expr,
      sym_primary_identifier_expr,
    STATE(13), 3,
      sym_construct_session_expr,
      sym_bop_expr,
      sym_primary_expr,
  [52] = 7,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_construct_session,
    ACTIONS(17), 1,
      sym_identifier,
    STATE(22), 1,
      sym_expr,
    ACTIONS(15), 2,
      sym_primary_true_expr,
      sym_primary_false_expr,
    STATE(11), 2,
      sym_primary_parenthesized_expr,
      sym_primary_identifier_expr,
    STATE(13), 3,
      sym_construct_session_expr,
      sym_bop_expr,
      sym_primary_expr,
  [78] = 7,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_construct_session,
    ACTIONS(17), 1,
      sym_identifier,
    STATE(17), 1,
      sym_expr,
    ACTIONS(15), 2,
      sym_primary_true_expr,
      sym_primary_false_expr,
    STATE(11), 2,
      sym_primary_parenthesized_expr,
      sym_primary_identifier_expr,
    STATE(13), 3,
      sym_construct_session_expr,
      sym_bop_expr,
      sym_primary_expr,
  [104] = 7,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_construct_session,
    ACTIONS(17), 1,
      sym_identifier,
    STATE(19), 1,
      sym_expr,
    ACTIONS(15), 2,
      sym_primary_true_expr,
      sym_primary_false_expr,
    STATE(11), 2,
      sym_primary_parenthesized_expr,
      sym_primary_identifier_expr,
    STATE(13), 3,
      sym_construct_session_expr,
      sym_bop_expr,
      sym_primary_expr,
  [130] = 7,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_construct_session,
    ACTIONS(17), 1,
      sym_identifier,
    STATE(20), 1,
      sym_expr,
    ACTIONS(15), 2,
      sym_primary_true_expr,
      sym_primary_false_expr,
    STATE(11), 2,
      sym_primary_parenthesized_expr,
      sym_primary_identifier_expr,
    STATE(13), 3,
      sym_construct_session_expr,
      sym_bop_expr,
      sym_primary_expr,
  [156] = 7,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_construct_session,
    ACTIONS(17), 1,
      sym_identifier,
    STATE(24), 1,
      sym_expr,
    ACTIONS(15), 2,
      sym_primary_true_expr,
      sym_primary_false_expr,
    STATE(11), 2,
      sym_primary_parenthesized_expr,
      sym_primary_identifier_expr,
    STATE(13), 3,
      sym_construct_session_expr,
      sym_bop_expr,
      sym_primary_expr,
  [182] = 7,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_construct_session,
    ACTIONS(17), 1,
      sym_identifier,
    STATE(16), 1,
      sym_expr,
    ACTIONS(15), 2,
      sym_primary_true_expr,
      sym_primary_false_expr,
    STATE(11), 2,
      sym_primary_parenthesized_expr,
      sym_primary_identifier_expr,
    STATE(13), 3,
      sym_construct_session_expr,
      sym_bop_expr,
      sym_primary_expr,
  [208] = 6,
    ACTIONS(5), 1,
      anon_sym_print,
    ACTIONS(7), 1,
      anon_sym_query,
    ACTIONS(9), 1,
      anon_sym_let,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    STATE(14), 2,
      sym_statement,
      aux_sym_source_file_repeat1,
    STATE(42), 3,
      sym_print_statement,
      sym_query_statement,
      sym_decl_statement,
  [230] = 1,
    ACTIONS(21), 9,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_with,
      anon_sym_role,
      sym_bop_eq,
      sym_bop_lt,
      sym_bop_gt,
      sym_bop_and,
      sym_bop_or,
  [242] = 1,
    ACTIONS(23), 9,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_with,
      anon_sym_role,
      sym_bop_eq,
      sym_bop_lt,
      sym_bop_gt,
      sym_bop_and,
      sym_bop_or,
  [254] = 1,
    ACTIONS(25), 9,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_with,
      anon_sym_role,
      sym_bop_eq,
      sym_bop_lt,
      sym_bop_gt,
      sym_bop_and,
      sym_bop_or,
  [266] = 6,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    ACTIONS(29), 1,
      anon_sym_print,
    ACTIONS(32), 1,
      anon_sym_query,
    ACTIONS(35), 1,
      anon_sym_let,
    STATE(14), 2,
      sym_statement,
      aux_sym_source_file_repeat1,
    STATE(42), 3,
      sym_print_statement,
      sym_query_statement,
      sym_decl_statement,
  [288] = 1,
    ACTIONS(38), 9,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_with,
      anon_sym_role,
      sym_bop_eq,
      sym_bop_lt,
      sym_bop_gt,
      sym_bop_and,
      sym_bop_or,
  [300] = 2,
    ACTIONS(42), 3,
      sym_bop_eq,
      sym_bop_lt,
      sym_bop_gt,
    ACTIONS(40), 6,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_with,
      anon_sym_role,
      sym_bop_and,
      sym_bop_or,
  [314] = 1,
    ACTIONS(40), 9,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_with,
      anon_sym_role,
      sym_bop_eq,
      sym_bop_lt,
      sym_bop_gt,
      sym_bop_and,
      sym_bop_or,
  [326] = 1,
    ACTIONS(44), 9,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_with,
      anon_sym_role,
      sym_bop_eq,
      sym_bop_lt,
      sym_bop_gt,
      sym_bop_and,
      sym_bop_or,
  [338] = 3,
    ACTIONS(46), 1,
      sym_bop_and,
    ACTIONS(42), 3,
      sym_bop_eq,
      sym_bop_lt,
      sym_bop_gt,
    ACTIONS(40), 5,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_with,
      anon_sym_role,
      sym_bop_or,
  [354] = 5,
    ACTIONS(46), 1,
      sym_bop_and,
    ACTIONS(48), 1,
      anon_sym_SEMI,
    ACTIONS(50), 1,
      anon_sym_role,
    ACTIONS(52), 1,
      sym_bop_or,
    ACTIONS(42), 3,
      sym_bop_eq,
      sym_bop_lt,
      sym_bop_gt,
  [372] = 4,
    ACTIONS(46), 1,
      sym_bop_and,
    ACTIONS(52), 1,
      sym_bop_or,
    ACTIONS(54), 1,
      anon_sym_with,
    ACTIONS(42), 3,
      sym_bop_eq,
      sym_bop_lt,
      sym_bop_gt,
  [387] = 4,
    ACTIONS(46), 1,
      sym_bop_and,
    ACTIONS(52), 1,
      sym_bop_or,
    ACTIONS(56), 1,
      anon_sym_RPAREN,
    ACTIONS(42), 3,
      sym_bop_eq,
      sym_bop_lt,
      sym_bop_gt,
  [402] = 4,
    ACTIONS(46), 1,
      sym_bop_and,
    ACTIONS(52), 1,
      sym_bop_or,
    ACTIONS(58), 1,
      anon_sym_RPAREN,
    ACTIONS(42), 3,
      sym_bop_eq,
      sym_bop_lt,
      sym_bop_gt,
  [417] = 4,
    ACTIONS(46), 1,
      sym_bop_and,
    ACTIONS(52), 1,
      sym_bop_or,
    ACTIONS(60), 1,
      anon_sym_SEMI,
    ACTIONS(42), 3,
      sym_bop_eq,
      sym_bop_lt,
      sym_bop_gt,
  [432] = 5,
    ACTIONS(62), 1,
      anon_sym_DQUOTE,
    ACTIONS(64), 1,
      anon_sym_LBRACE,
    ACTIONS(67), 1,
      sym_query_string_segment,
    STATE(25), 1,
      aux_sym_query_string_repeat1,
    STATE(37), 1,
      sym_query_decl,
  [448] = 5,
    ACTIONS(70), 1,
      anon_sym_DQUOTE,
    ACTIONS(72), 1,
      anon_sym_LBRACE,
    ACTIONS(74), 1,
      sym_query_string_segment,
    STATE(27), 1,
      aux_sym_query_string_repeat1,
    STATE(37), 1,
      sym_query_decl,
  [464] = 5,
    ACTIONS(72), 1,
      anon_sym_LBRACE,
    ACTIONS(74), 1,
      sym_query_string_segment,
    ACTIONS(76), 1,
      anon_sym_DQUOTE,
    STATE(25), 1,
      aux_sym_query_string_repeat1,
    STATE(37), 1,
      sym_query_decl,
  [480] = 2,
    STATE(57), 1,
      sym_role,
    ACTIONS(78), 3,
      anon_sym_user,
      anon_sym_assistant,
      anon_sym_system,
  [489] = 1,
    ACTIONS(80), 4,
      ts_builtin_sym_end,
      anon_sym_print,
      anon_sym_query,
      anon_sym_let,
  [496] = 2,
    STATE(52), 1,
      sym_role,
    ACTIONS(78), 3,
      anon_sym_user,
      anon_sym_assistant,
      anon_sym_system,
  [505] = 4,
    ACTIONS(82), 1,
      anon_sym_String,
    ACTIONS(84), 1,
      anon_sym_Session,
    STATE(48), 1,
      sym_type,
    STATE(53), 1,
      sym_primitive_type,
  [518] = 3,
    ACTIONS(86), 1,
      anon_sym_SEMI,
    ACTIONS(88), 1,
      anon_sym_requires,
    ACTIONS(90), 1,
      anon_sym_role,
  [528] = 2,
    ACTIONS(94), 1,
      sym_query_string_segment,
    ACTIONS(92), 2,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
  [536] = 1,
    ACTIONS(96), 3,
      anon_sym_SEMI,
      anon_sym_requires,
      anon_sym_role,
  [542] = 1,
    ACTIONS(98), 3,
      anon_sym_SEMI,
      anon_sym_requires,
      anon_sym_role,
  [548] = 2,
    ACTIONS(102), 1,
      sym_query_string_segment,
    ACTIONS(100), 2,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
  [556] = 2,
    ACTIONS(106), 1,
      sym_query_string_segment,
    ACTIONS(104), 2,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
  [564] = 2,
    ACTIONS(108), 1,
      anon_sym_q_DQUOTE,
    STATE(32), 1,
      sym_query_string,
  [571] = 1,
    ACTIONS(110), 1,
      anon_sym_COLON,
  [575] = 1,
    ACTIONS(112), 1,
      anon_sym_let,
  [579] = 1,
    ACTIONS(114), 1,
      anon_sym_LPAREN,
  [583] = 1,
    ACTIONS(116), 1,
      anon_sym_SEMI,
  [587] = 1,
    ACTIONS(118), 1,
      anon_sym_LPAREN,
  [591] = 1,
    ACTIONS(120), 1,
      anon_sym_EQ,
  [595] = 1,
    ACTIONS(122), 1,
      anon_sym_EQ,
  [599] = 1,
    ACTIONS(124), 1,
      sym_identifier,
  [603] = 1,
    ACTIONS(126), 1,
      sym_identifier,
  [607] = 1,
    ACTIONS(128), 1,
      anon_sym_EQ,
  [611] = 1,
    ACTIONS(130), 1,
      ts_builtin_sym_end,
  [615] = 1,
    ACTIONS(132), 1,
      anon_sym_COLON,
  [619] = 1,
    ACTIONS(134), 1,
      anon_sym_SEMI,
  [623] = 1,
    ACTIONS(136), 1,
      anon_sym_SEMI,
  [627] = 1,
    ACTIONS(138), 1,
      anon_sym_EQ,
  [631] = 1,
    ACTIONS(140), 1,
      anon_sym_SEMI,
  [635] = 1,
    ACTIONS(142), 1,
      sym_llm,
  [639] = 1,
    ACTIONS(144), 1,
      anon_sym_String,
  [643] = 1,
    ACTIONS(146), 1,
      anon_sym_SEMI,
  [647] = 1,
    ACTIONS(148), 1,
      anon_sym_RBRACE,
  [651] = 1,
    ACTIONS(150), 1,
      anon_sym_RPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 26,
  [SMALL_STATE(4)] = 52,
  [SMALL_STATE(5)] = 78,
  [SMALL_STATE(6)] = 104,
  [SMALL_STATE(7)] = 130,
  [SMALL_STATE(8)] = 156,
  [SMALL_STATE(9)] = 182,
  [SMALL_STATE(10)] = 208,
  [SMALL_STATE(11)] = 230,
  [SMALL_STATE(12)] = 242,
  [SMALL_STATE(13)] = 254,
  [SMALL_STATE(14)] = 266,
  [SMALL_STATE(15)] = 288,
  [SMALL_STATE(16)] = 300,
  [SMALL_STATE(17)] = 314,
  [SMALL_STATE(18)] = 326,
  [SMALL_STATE(19)] = 338,
  [SMALL_STATE(20)] = 354,
  [SMALL_STATE(21)] = 372,
  [SMALL_STATE(22)] = 387,
  [SMALL_STATE(23)] = 402,
  [SMALL_STATE(24)] = 417,
  [SMALL_STATE(25)] = 432,
  [SMALL_STATE(26)] = 448,
  [SMALL_STATE(27)] = 464,
  [SMALL_STATE(28)] = 480,
  [SMALL_STATE(29)] = 489,
  [SMALL_STATE(30)] = 496,
  [SMALL_STATE(31)] = 505,
  [SMALL_STATE(32)] = 518,
  [SMALL_STATE(33)] = 528,
  [SMALL_STATE(34)] = 536,
  [SMALL_STATE(35)] = 542,
  [SMALL_STATE(36)] = 548,
  [SMALL_STATE(37)] = 556,
  [SMALL_STATE(38)] = 564,
  [SMALL_STATE(39)] = 571,
  [SMALL_STATE(40)] = 575,
  [SMALL_STATE(41)] = 579,
  [SMALL_STATE(42)] = 583,
  [SMALL_STATE(43)] = 587,
  [SMALL_STATE(44)] = 591,
  [SMALL_STATE(45)] = 595,
  [SMALL_STATE(46)] = 599,
  [SMALL_STATE(47)] = 603,
  [SMALL_STATE(48)] = 607,
  [SMALL_STATE(49)] = 611,
  [SMALL_STATE(50)] = 615,
  [SMALL_STATE(51)] = 619,
  [SMALL_STATE(52)] = 623,
  [SMALL_STATE(53)] = 627,
  [SMALL_STATE(54)] = 631,
  [SMALL_STATE(55)] = 635,
  [SMALL_STATE(56)] = 639,
  [SMALL_STATE(57)] = 643,
  [SMALL_STATE(58)] = 647,
  [SMALL_STATE(59)] = 651,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primary_expr, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primary_identifier_expr, 1, 0, 1),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 1, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primary_parenthesized_expr, 3, 0, 2),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bop_expr, 3, 0, 4),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_construct_session_expr, 4, 0, 7),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query_statement, 6, 0, 12),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decl_statement, 6, 0, 14),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_query_string_repeat1, 2, 0, 11),
  [64] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_query_string_repeat1, 2, 0, 11), SHIFT_REPEAT(40),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_query_string_repeat1, 2, 0, 11), SHIFT_REPEAT(33),
  [70] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [72] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [76] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 2, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query_statement, 4, 0, 3),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_query_string_repeat1, 1, 0, 8),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_query_string_repeat1, 1, 0, 8),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query_string, 3, 0, 10),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query_string, 2, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_query_decl, 6, 0, 16),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query_decl, 6, 0, 16),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_query_string_repeat1, 1, 0, 9),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_query_string_repeat1, 1, 0, 9),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primitive_type, 1, 0, 5),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primitive_type, 1, 0, 6),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [130] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_role, 1, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query_statement, 6, 0, 13),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_print_statement, 4, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query_statement, 8, 0, 15),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_haibara_parser(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
